# Базовый образ для сборки
FROM node:20-alpine AS build

WORKDIR /frontend

# Копируем package.json для кеширования зависимостей
COPY package*.json ./
RUN npm install

# Копируем остальной код и собираем приложение
COPY . .
RUN npm run build

# Финальный легковесный образ
FROM node:20-alpine

WORKDIR /frontend

# Копируем только собранные файлы
COPY --from=build /frontend/build /frontend/build