name: Run App, Test and Cleanup

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_app:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DB_NAME=gg
          DB_USER=gleb
          DB_PASS=1234
          DB_HOST=db
          DB_PORT=5432
          TEST_DB_NAME=gg_test
          TEST_DB_USER=gleb_test
          TEST_DB_PASS=1234
          TEST_DB_HOST=db_test
          TEST_DB_PORT=5430
          EOF

      - name: Build and run containers
        run: sudo docker-compose up -d

      - name: Wait for services to initialize
        run: sleep 10

      - name: Run tests in backend container
        run: sudo docker-compose exec backend pytest --maxfail=1 --disable-warnings -q

      - name: Tear down containers and remove volumes
        run: sudo docker-compose down -v
