name: Build and Test FastAPI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file from environment variables
        run: |
          echo "DB_NAME=gg" > .env
          echo "DB_USER=gleb" >> .env
          echo "DB_PASS=1234" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "TEST_DB_NAME=gg_test" >> .env
          echo "TEST_DB_USER=gleb_test" >> .env
          echo "TEST_DB_PASS=1234" >> .env
          echo "TEST_DB_HOST=db_test" >> .env
          echo "TEST_DB_PORT=5430" >> .env

      - name: Build and start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml --env-file .env up -d

  wait_for_backend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          sleep 10
          curl --retry 10 --retry-delay 5 --max-time 30 http://localhost:8000

  shutdown:
    runs-on: ubuntu-latest
    needs: [build, wait_for_backend]  # Waits for build and wait_for_backend to complete
    steps:
      - name: Shut down containers
        run: |
          docker-compose down
