name: Run App, Test and Cleanup

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_app:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run containers
        run: docker-compose up -d

      - name: Wait for services to initialize
        run: sleep 10

      - name: Run tests in backend container
        run: docker-compose exec backend pytest --maxfail=1 --disable-warnings -q

      - name: Tear down containers and remove volumes
        run: docker-compose down -v
