name: Build and Test FastAPI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and start Docker Compose services with environment variables
        run: |
          DB_NAME=gg \
          DB_USER=gleb \
          DB_PASS=1234 \
          DB_HOST=db \
          DB_PORT=5432 \
          TEST_DB_NAME=gg_test \
          TEST_DB_USER=gleb_test \
          TEST_DB_PASS=1234 \
          TEST_DB_HOST=db_test \
          TEST_DB_PORT=5430 \
          docker-compose -f docker-compose.yml up -d

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          sleep 10
          curl --retry 10 --retry-delay 5 --max-time 30 http://localhost:8000

      - name: Shut down containers
        run: |
          docker-compose down
