name: Build and Test FastAPI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .env file for Docker Compose
        run: |
          cp .env .env # Убедитесь, что .env доступен для Docker Compose

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          # Пауза, чтобы дать контейнерам время для запуска
          sleep 10
          # Проверка, что приложение доступно на порту 8000
          curl --retry 10 --retry-delay 5 --max-time 30 http://localhost:8000

      - name: Shut down containers
        run: |
          docker-compose down
