name: Build and Test FastAPI with Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file from environment variables
        run: |
          echo "DB_NAME=gg" > .env
          echo "DB_USER=gleb" >> .env
          echo "DB_PASS=1234" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "TEST_DB_NAME=gg_test" >> .env
          echo "TEST_DB_USER=gleb_test" >> .env
          echo "TEST_DB_PASS=1234" >> .env
          echo "TEST_DB_HOST=db_test" >> .env
          echo "TEST_DB_PORT=5430" >> .env

      - name: Build and start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml --env-file .env up -d

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          for i in {1..20}; do
            if curl --silent http://localhost:8000 > /dev/null; then
              echo "Backend is ready!"
              exit 0
            else
              echo "Backend not ready yet, waiting..."
              sleep 5
            fi
          done
          echo "Backend did not become ready in time."
          exit 1

      - name: Run tests inside backend container
        run: |
          docker-compose exec -T backend pytest

      - name: Shut down containers
        run: |
          docker-compose down
