name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Buildx
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -sSL https://github.com/docker/buildx/releases/download/v0.8.0/buildx-v0.8.0.linux-amd64 > ~/.docker/cli-plugins/docker-buildx
          chmod +x ~/.docker/cli-plugins/docker-buildx

      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for backend to start
        run: |
          curl --retry 5 --retry-delay 5 http://localhost:8000  

      - name: Clean up
        run: docker-compose down -v
